name: CI

# triggers upon push/pull request for the master branch
on:
  push:
    branches: [ master, feature/ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/linux-64.txt') }}

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v1
        with: 
          auto-update-conda: true
          activate-environment: poandy
          python-version: 3.8.5
          channels: conda-forge, defaults
          channel-priority: true
          environment-file: requirements/linux-64.txt
          use-only-tar-bz2: true

      - shell: bash -l {0}
        run: |
          conda info
          conda list
    
    #   - name: Install dependencies
    #     run: conda create -n poandy python=3.8.5 --file requirements/linux-64.txt

    #   - name: Activate virtual environment
    #     run: conda activate poandy

      - name: Test with Pytest
        run: python -m pytest 
    
      - name: Ensure code is formatted with Black
        run: python -m black .

    #   - name: Deactivate virtual environment
    #     run: conda deactivate poandy
