name: CI

# triggers upon push/pull request for the master branch
on:
  push:
    branches: [ master, feature/ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('requirements/win-64.txt') }}

      - name: Write the secrets.json file 
        uses: RollyPeres/base64-to-path@v1
        with:
          filename: ${{ github.workspace }}/secrets.json
          encodedString: ${{ secrets.SECRETS_BASE64_FILE }}

      - name: Set up Conda and activate virtual environment
        uses: conda-incubator/setup-miniconda@v1
        with: 
          auto-update-conda: true
          activate-environment: poandy
          python-version: 3.8.5
          channels: conda-forge, defaults
          channel-priority: true
          environment-file: requirements/win-64.txt
          use-only-tar-bz2: true

      # - shell: bash -l {0}
      #   run: |
      #     conda info
      #     conda list
    
    #   - name: Install dependencies
    #     run: conda create -n poandy python=3.8.5 --file requirements/linux-64.txt

    #   - name: Activate virtual environment
    #     run: conda activate poandy

      - name: Run automated tests with PyTest
        run: conda run -n poandy python -m pytest 
    
      - name: Ensure code has been formatted with Black
        run: conda run -n poandy python -m black .

    #   - name: Deactivate virtual environment
    #     run: conda deactivate poandy
